### ISSUE TITLE
Demandes d'informations

### ISSUE THREAD

**Issue by WinXaito** [pLaborderie/iut-notes#2]
Bonjour,

Pour mes études je recherche un logiciel de prise de notes. Pourriez-vous me fournir quelques informations concernant celui que vous développez ?

- Est il installable en l'état actuel ? Y a t'il une documentation pour ceci ? (j'imagine qu'il s'agit d'un serveur NodeJS)
- Quel est le mode d'enregistrement des données ? (Fichier, base de données [mysql, sqlite, .. ?])
- Est-il possible d'utiliser un éditeur hors-ligne (une api est-il prévue ?)
- Les notes peuvent-elles être privé ou sont-elles obligatoirement publiques ?

Je vous remercie d'avance.

**Comment by pLaborderie** [comment]
Bonjour,

En effet, l'application est un serveur NodeJS/GraphQL. Il n'y a pas encore de documentation concernant l'installation, je n'avais pas trop de temps à dédier au projet ces derniers jours.
Les données sont enregistrées sur une base de données Postgres hébergée chez DigitalOcean.
L'application étant une PWA, un mode hors ligne est en effet prévu, ainsi qu'un système de notes privées (toutes publiques pour l'instant).

Pour l'instant, le projet cible en particulier mon IUT le temps du développement, mais pourra s'étendre vers d'autres cibles une fois un peu plus abouti :)
Si vous voulez essayer l'application cependant, elle est disponible [ici](https://www.iut-notes.fr).

Si vous cherchez un logiciel de prise de notes uniquement hors ligne, je ne peux que vous conseiller le logiciel [Boostnote](https://boostnote.io/) !
